name: "anyone-push-back-repo"
author: "Zhang Nan (zhang_nan_163@163.com)"
branding:
  icon: git-commit
  color: green
description: "This action help you push back to pull request when user made changes in action. Then use it to push back to your repo"
inputs:
  strategy-option:
    description: "action will rebase to target branch with specific strategy. usually will use -X<strategy-option>. default is 'ours'. Please reference here: https://www.atlassian.com/git/tutorials/using-branches/merge-strategy"
    required: false
    default: "ours"
  actor:
    description: "commiter username. default will retrieve from actor environment variable"
    required: false
    default: ${{ github.actor }}
  actor-email:
    description: "committer email. defail will use `actor`@users.noreply.github.com"
    required: false
    default: ${{ github.actor }}@users.noreply.github.com
outputs:
  modified:
    description: 'modified flag 1 as "true" or 0 as "false"'
    value: ${{ steps.committer.outputs.modified }}
runs:
  using: "composite"
  steps:
    - name: Grant execution permission
      run: |
        chmod +x ${{ github.action_path }}/git-status.sh
        chmod +x ${{ github.action_path }}/git-push.sh
      shell: bash
    - name: Commit changes
      id: committer
      run: |
        input_actor=$(if [[ "${{ inputs.actor }}" == '' ]]; then echo 0; else echo "${{ inputs.actor }}"; fi)
        input_actor_email=$(if [[ "${{ inputs.actor-email }}" == '' ]]; then echo 0; else echo "${{ inputs.actor-email }}"; fi)
        github_head_ref=$(if [[ "${{github.head_ref}}" == '' ]]; then echo 0; else echo "${{github.head_ref}}"; fi)
        github_base_ref=$(if [[ "${{github.base_ref}}" == '' ]]; then echo 0; else echo "${{github.base_ref}}"; fi)
        github_ref=$(if [[ "${{github.ref}}" == '' ]]; then echo 0; else echo "${{github.ref}}"; fi)
        github_workflow= $(if [[ "${{github.workflow}}" == '' ]]; then echo 0; else echo "${{github.workflow}}"; fi)
        github_row_number=$(if [[ "${{github.run_number}}" == '' ]]; then echo 0; else echo "${{github.run_number}}"; fi)
        input_strategy_option=$(if [[ "${{ inputs.strategy-option }}" == '' ]]; then echo 0; else echo "${{ inputs.strategy-option }}"; fi)

        ${{ github.action_path }}/git-push.sh $input_actor $input_actor_email $github_head_ref $github_base_ref $github_ref $input_strategy_option $github_workflow $github_row_number
      shell: bash
