name: "anyone-push-back-repo"
author: "Zhang Nan (zhang_nan_163@163.com)"
branding:
  icon: git-commit
  color: green
description: "This action help you push back to pull request when user made changes in action. Then use this action to push back to your repo"
inputs:
  user-name:
    description: "commit config user.name"
    required: false
    default: "anyone-developer"
  user-email:
    description: "commit config user.email"
    required: false
    default: "zhang_nan_163@163.com"
outputs:
  modified:
    description: 'modified flag 1 as "true" or 0 as "false"'
    value: ${{ steps.git-check.outputs.modified }}
runs:
  using: "composite"
  steps:
    - name: Check modification
      id: git-check
      run: echo ::set-output name=modified::$(if [[ "$(git status -s)" == '' ]]; then echo 0; else echo 1; fi)
      shell: bash
    - run: echo $GITHUB_REF
      shell: bash
    - run: echo $GITHUB_HEAD_REF
      shell: bash
    - run: echo $GITHUB_BASE_REF
      shell: bash 
    - name: Grant execution permission
      run: chmod +x $GITHUB_ACTION_PATH/git-push.sh
      shell: bash
    - name: Commit changes
      run: $GITHUB_ACTION_PATH/git-push.sh ${{steps.git-check.outputs.modified}} ${{inputs.user-name}} ${{inputs.user-email}} ${{github.workflow}} ${{github.run_number}} ${{github.ref}}
      shell: bash
