name: "anyone-push-back-repo"
author: "Zhang Nan (zhang_nan_163@163.com)"
branding:
  icon: git-commit
  color: green
description: "This action help you push back to pull request when user made changes in action. Then use it to push back to your repo"
inputs:
  strategy-option:
    description: "action will rebase to target branch with specific strategy. usually will use -X<strategy-option>. default is 'ours'. Please reference here: https://www.atlassian.com/git/tutorials/using-branches/merge-strategy"
    required: false
    default: "ours"
  actor:
    description: "commiter username. default will retrieve from actor environment variable"
    required: false
    default: ${{ github.actor }}
  actor-email:
    description: "committer email. defail will use `actor`@users.noreply.github.com"
    required: false
    default: ${{ github.actor }}@users.noreply.github.com
outputs:
  modified:
    description: 'modified flag 1 as "true" or 0 as "false"'
    value: ${{ steps.git-check.outputs.modified }}
runs:
  using: "composite"
  steps:
    - name: Check modification
      id: git-check
      run: echo ::set-output name=modified::$(if [[ "$(git status -s)" == '' ]]; then echo 0; else echo 1; fi)
      shell: bash
    - name: Grant execution permission
      run: chmod +x ${{ github.action_path }}/git-push.sh
      shell: bash
    - name: Commit changes
      run: ${{ github.action_path }}/git-push.sh \
        ${{ steps.git-check.outputs.modified }} \
        ${{ inputs.actor }} \
        ${{ inputs.actor-email }} \
        $(if [[ "${{github.head_ref}}" == '' ]]; then 0; else ${{github.head_ref}}; fi) \
        $(if [[ "${{github.base_ref}}" == '' ]]; then 0; else ${{github.base_ref}}; fi) \
        $(if [[ "${{github.ref}}" == '' ]]; then 0; else ${{github.ref}}; fi) \
        ${{ inputs.strategy-option}} \
        ${{ github.workflow }} \
        ${{ github.run_number }}
      shell: bash
