name: release-test
on:
  schedule:
    - cron:  '0 9 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, edited, ready_for_review, reopened, synchronize]
jobs:
  test-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Remove test file
        run: rm -f testfile
        shell: bash
      - name: Generate test file
        run: date +%s > testfile
        shell: bash
      - name: Push changes to remote
        id: create-push-change
        uses: anyone-developer/anyone-push-back-repo@develop
      