name: test-create-file
on:
  schedule:
    - cron: "0 9 * * *"
jobs:
  create-test-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: import gpg
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v3.0.1
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true
      - name: Generate test file
        run: date +%s > testfile
        shell: bash
      - name: Push changes to remote
        id: create-push-change
        uses: anyone-developer/anyone-push-back-repo@main
        with:
          strategy-option: ours
          actor: Edward-Roshan
          actor-email:  zhang_nan_163@163.com
